class BranchData{
    List codes = [
    'ai',
    'bm',
    'bt',
    'ce',
    'ch',
    'co',
    'cs',
    'd',
    'ee',
    'ep',
    'es',
    'ic',
    'ms',
    'me',
    'ma',
  ];

  List branchName = [
    'Artificial Intelligence',
    'Biomedical Engineering',
    'Biotechnology',
    'Civil Engineering',
    'Chemical Enginnering',
    'Computational Engineering',
    'Computer Science and Engineering',
    'Design',
    'Electrical Engineering',
    'Engineering Physics',
    'Engineering Science',
    'Industrial Chemistry',
    'Material Science and Metallurgical Engineering',
    'Mechanical and Aerospace Engineering',
    'Mathematics',
  ];

  List pgCodes = [
    'ai',
    'am',
    'bm',
    'bt',
    'cc',//climate change
    'ce',
    'ch',
    'co',
    'cs',
    'd',
    'ee',
    'et',
    'ep',
    'es',
    'em',
    'ew',
    'la',
    'ic',
    'is',
    'ms',
    'me',
    'ma',
    'ph',
    'pb',
    'sm',
    'mi',
    'op',
  ];

  List pgBranchName = [
    'Artificial Intelligence',
    'Additive Manufacturing',
    'Biomedical Engineering',
    'Biotechnology',
    'Climate Change',
    'Civil Engineering',
    'Chemical Enginnering',
    'Computational Engineering',
    'Computer Science and Engineering',
    'Design',
    'Electrical Engineering',
    'Energy Science and Engineering',
    'Engineering Physics',
    'Engineering Science',
    'Entrepreneurship and Management',
    'E-Waste Resource Engineering & Management',
    'Liberal Arts',
    'Industrial Chemistry',
    'Integrated Sensor Systems',
    'Material Science and Metallurgical Engineering',
    'Mechanical and Aerospace Engineering',
    'Mathematics',
    'Physics',
    'Polymers & Bio Systems Engineering',
    'Smart Mobility',
    'Medical Device Innovation',
    'Opthalmic Engineering',
  ];
}