
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: "${dotenv.env['API_KEY_ANDROID']}",
    appId: '1:104215692812:android:2cde82e8aa5967211b9029',
    messagingSenderId: '104215692812',
    projectId: 'sunshine-iith-newapp',
    databaseURL: 'https://sunshine-iith-newapp-default-rtdb.firebaseio.com',
    storageBucket: 'sunshine-iith-newapp.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: "${dotenv.env['API_KEY_IOS']}",
    appId: '1:104215692812:ios:927c7a6d91ccffd71b9029',
    messagingSenderId: '104215692812',
    projectId: 'sunshine-iith-newapp',
    databaseURL: 'https://sunshine-iith-newapp-default-rtdb.firebaseio.com',
    storageBucket: 'sunshine-iith-newapp.appspot.com',
    androidClientId: '104215692812-0r6a5dl8reojl3gvm4mjg57oo7oklo9v.apps.googleusercontent.com',
    iosClientId: '104215692812-uqqfaokqk5cqdppac2ngt9vhm8hp404l.apps.googleusercontent.com',
    iosBundleId: 'com.iith.sunshineIith',
  );
}
